# version: '3'
# services:
#   db:
#     container_name: sso_db
#     image: postgres:13
#     environment:
#         - POSTGRES_PASSWORD=password123
#         - POSTGRES_DB=sso_db
#     volumes:
#       - ./db/initdb.d:/docker-entrypoint-initdb.d
#     ports:
#       - '5445:5432'
version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5454:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
 
volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  postgres:
    driver: bridge